repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace

- repo: https://github.com/tofuutils/pre-commit-opentofu
  rev: v1.0.4
  hooks:
    - id: tofu_fmt
    - id: tofu_docs
      args:
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true