repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.96.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate

- repo: local
  hooks:
    - id: terraform-docs
      name: terraform-docs
      language: docker_image
      entry: quay.io/terraform-docs/terraform-docs:latest
      args: ["markdown", "table", "--output-file", "README.md", "./Project_A"]
      pass_filenames: false