repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace

- repo: https://github.com/tofuutils/pre-commit-opentofu
  rev: v1.0.4
  hooks:
    - id: tofu_fmt
    - id: tofu_validate
    - id: tofu_docs
      args:
        - markdown=table
        - --output-file=TF_Project_B.md
        # - --hook-config=--add-to-existing-file=true     # Boolean. true or false
        # - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
      # args: ["markdown", "table", "--output-file", "TF_Project_B.md", "./Project_B"]

# - repo: local
#   hooks:
#     - id: terraform-docs
#       name: terraform-docs
#       language: docker_image
#       entry: quay.io/terraform-docs/terraform-docs:latest
#       args: ["markdown", "table", "--output-file", "TF_Project_A.md", "./Project_A"]
#       pass_filenames: false